### ISSUE TITLE
Inconsistent use of core superclass names

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/modl.uk#10]
Section 7.2 'Class Inheritance' says `The core superclasses are str, number, arr and map.` but the base tests sometimes use `array` instead of `arr` and `num` instead of `number`. Should we be using the full names, the abbreviated names, or are both to be allowed?

What should be the behaviour if a user defines a class using one of these full or abbreviated names?

**Comment by alexdalitz** [comment]
Personally, I'd have thought that just using the short names would work.

Users should _not_ be able to redefine these base classes! We should probably add some `error_tests` for that.

Thanks!

**Comment by twalmsley** [comment]
Short names seem better for space saving, and that would make these into reserved class names:
`str`
`num`
`arr`
`map`

Can be closed when the spec is updated.

**Comment by elliottinvent** [comment]
Have made the change as suggested, using `num` instead of `number`
