### ISSUE TITLE
Class/Method id and name fields

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/modl.uk#12]
Are both `id` and `name` required for a classes and methods? (i.e. its an error if one is missing)

All the examples in the spec seem to use both but it isn't specified whether both are mandatory. Classes can be shorter if, say, `id` is mandatory but `name` is optional.

**Comment by elliottinvent** [comment]
No, names aren't required – well spotted. 

I've made it clearer in the spec:
https://modl.uk/specification#classes
https://modl.uk/specification#custom-methods
