### ISSUE TITLE
Missing *supertype

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/modl.uk#5]
Section 7.3 Key Assignment has an example class without a `*supertype` field but the `*supertype` is mandatory according to the previous section. The playground doesn't pick up the error.

There is also a missing `]` at the end of the line `[title;name;job_title`
One for @elliottinvent ?

**Comment by elliottinvent** [comment]
I'll correct the missing `]`, good spot. 

@alexdalitz what are your thoughts on how we should deal with missing superclasses? How does the interpreter deal with it currently? I suppose for character efficiency it would be good if we could use some kind of superclass inference.

**Comment by elliottinvent** [comment]
@alexdalitz Checking over the development history of the interpreter I think we did exactly that – I will update spec.

**Comment by alexdalitz** [comment]
Yes I'm pretty sure we use supertype of the parent hierarchy if it is not defined
